[build]
  command = "dotnet publish CALC-WEBD.csproj -c Release -o publish-directory"
  publish = "publish-directory"
  base = "."

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200














