[build]
base = "CALC-WEBD"
publish = "."
command = "dotnet build CALC-WEBD.csproj"

[[redirects]]
from = "/*"
to = "/index.html"
status = 200


[[redirects]]
from = "/*"
to = "/index.html"
status = 200



